# Generated by Django 6.0.2 on 2026-02-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_unique_together_transaction_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cost',
        ),
    ]
